version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            - yum -y update
            - echo Installing MkDocs
            - pip install mkdocs
    pre_build:
        commands:
            - echo In pre_build phase..
            - echo Current directory is $CODEBUILD_SRC_DIR
            - ls -la
    build:
        commands:
            - cd docs/user-guide
            - mkdocs build
artifacts:
    files:
        - '**/*'
    base-directory: docs/user-guide
    name: DocBuildOutput
